name: luna_test
description: "LUNA - AI-Powered Relationship & Personal Growth App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Storage & Database
  shared_preferences: ^2.3.2
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_analytics: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true