// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmeE-DJmAyFJzpkcf7gaYQ9ddkwe6zdO4',
    appId: '1:396183924939:web:58c4966025bdbf90872b4e',
    messagingSenderId: '396183924939',
    projectId: 'luna-e1ad5',
    authDomain: 'luna-e1ad5.firebaseapp.com',
    storageBucket: 'luna-e1ad5.firebasestorage.app',
    measurementId: 'G-J1S1G0D6W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmeE-DJmAyFJzpkcf7gaYQ9ddkwe6zdO4',
    appId: '1:396183924939:android:58c4966025bdbf90872b4e',
    messagingSenderId: '396183924939',
    projectId: 'luna-e1ad5',
    storageBucket: 'luna-e1ad5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmeE-DJmAyFJzpkcf7gaYQ9ddkwe6zdO4',
    appId: '1:396183924939:ios:58c4966025bdbf90872b4e',
    messagingSenderId: '396183924939',
    projectId: 'luna-e1ad5',
    storageBucket: 'luna-e1ad5.firebasestorage.app',
    iosClientId: '396183924939-0123456789abcdef.apps.googleusercontent.com',
    iosBundleId: 'com.example.lunaTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmeE-DJmAyFJzpkcf7gaYQ9ddkwe6zdO4',
    appId: '1:396183924939:ios:58c4966025bdbf90872b4e',
    messagingSenderId: '396183924939',
    projectId: 'luna-e1ad5',
    storageBucket: 'luna-e1ad5.firebasestorage.app',
    iosClientId: '396183924939-0123456789abcdef.apps.googleusercontent.com',
    iosBundleId: 'com.example.lunaTest',
  );
}